# Generated by Django 5.1.5 on 2025-02-28 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatepass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fastag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastag_id', models.CharField(max_length=50, unique=True)),
                ('fastag_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fastag_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20)),
                ('valid_till', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('TRUCK', 'Truck'), ('BUS', 'Bus'), ('MOTORCYCLE', 'Motorcycle')], max_length=50)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('fastag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle', to='vehicle.fastag')),
                ('vehicle_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle', to='gatepass.vehicle')),
            ],
            options={
                'ordering': ['vehicle_number'],
            },
        ),
    ]
