# Generated by Django 5.1.5 on 2025-02-28 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=11)),
                ('vehicle_colour', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('voucher_type', models.CharField(max_length=100)),
                ('gatepass_type', models.CharField(choices=[('Returnable', 'Returnable'), ('Non-Returnable', 'Non-Returnable')], max_length=20)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('stock_date', models.DateField(blank=True, null=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatepass', to='gatepass.branch')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatepass', to='gatepass.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatepass', to='gatepass.vehicle')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
